apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}-${{ values.branch }}
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
  annotations:
    backstage.io/source-location: url:${{ values.source_repository_app }}
    backstage.io/kubernetes-id: ${{ values.component_id }}-${{ values.branch }}
spec:
  type: service
  lifecycle: development
  owner: ${{ values.owner | dump }}
