---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-${{ values.branch }}
  namespace: ${{ values.gitops_namespace }}
  labels:
    rht-gitops.com/${{ values.gitops_namespace }}: ${{ values.component_id }}-${{ values.branch }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: ${{ values.gitops_project }}
  source:
    repoURL: ${{ values.source_repository }}
    targetRevision: main
    path: ./app/helm/parasol-store
    helm:
      values: |
        nameOverride: ${{ values.component_id }}
        user: ${{ values.owner }}
        image:
          organization: ${{values.image_organization}}
          host: ${{ values.image_host }}
          name: ${{ values.image_name }}
          tag: ${{ values.image_tag }}
          pullPolicy: Always
        registry:
          enabled: false
        database:
          namespace: ${{ values.database_namespace }} 
          service: ${{ values.database_service }}
          name: ${{ values.database_name }}
          user: ${{ values.database_user }}
          password: ${{ values.database_password }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ${{ values.gitops_namespace }}
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy